import type { IEmojiItem, IEmojiReaction } from '@social/types/commons.type';
import thumbUp from '@social/animations/emojis/Thumbs-up.json';
import heart from '@social/animations/emojis/heart.json';
import laughing from '@social/animations/emojis/laughing.json';
import astonished from '@social/animations/emojis/astonished.json';
import crying from '@social/animations/emojis/crying.json';
import rage from '@social/animations/emojis/rage.json';

export const emojiReactions: IEmojiReaction[] = [
  {
    id: 'emoji-like-1',
    emoji: '👍',
    label: 'Thích',
    value: 1,
    color: '#1877F2',
    reSource: thumbUp,
  },
  {
    id: 'emoji-love-2',
    emoji: '❤️',
    label: 'Yêu thích',
    value: 2,
    color: '#F02849',
    reSource: heart,
  },

  {
    id: 'emoji-haha-3',
    emoji: '😆',
    label: 'Haha',
    value: 3,
    color: '#F7B125',
    reSource: laughing,
  },
  {
    id: 'emoji-wow-4',
    emoji: '😮',
    label: 'Wow',
    value: 4,
    color: '#F7B125',
    reSource: astonished,
  },
  {
    id: 'emoji-sad-5',
    emoji: '😭',
    label: 'Buồn',
    value: 5,
    color: '#8B9DC3',
    reSource: crying,
  },

  {
    id: 'emoji-angry-6',
    emoji: '😡',
    label: 'Phẫn nộ',
    value: 6,
    color: '#E24C4B',
    reSource: rage,
  },
];

const emojiData: IEmojiItem[] = [
  {
    id: 'emoji-smile',
    emoji: '😊',
    label: 'hạnh phúc',
    slug: 'hanh-phuc',
  },
  {
    id: 'emoji-heart-eyes',
    emoji: '🥰',
    label: 'được yêu',
    slug: 'duoc-yeu',
  },
  {
    id: 'emoji-heart-eyes-love',
    emoji: '😍',
    label: 'đáng yêu',
    slug: 'dang-yeu',
  },
  {
    id: 'emoji-star-struck',
    emoji: '🤩',
    label: 'hào hứng',
    slug: 'hao-hung',
  },
  {
    id: 'emoji-zany',
    emoji: '🤪',
    label: 'điên',
    slug: 'dien',
  },
  {
    id: 'emoji-grin',
    emoji: '😁',
    label: 'sung sướng',
    slug: 'sung-suong',
  },
  {
    id: 'emoji-yum',
    emoji: '😋',
    label: 'khờ khạo',
    slug: 'kho-khao',
  },
  {
    id: 'emoji-innocent',
    emoji: '😇',
    label: 'có phúc',
    slug: 'co-phuc',
  },
  {
    id: 'emoji-pensive',
    emoji: '😔',
    label: 'buồn',
    slug: 'buon',
  },
  {
    id: 'emoji-grinning',
    emoji: '😀',
    label: 'biết ơn',
    slug: 'biet-on',
  },
  {
    id: 'emoji-heart-eyes-2',
    emoji: '🥰',
    label: 'đang yêu',
    slug: 'dang-yeu',
  },
  {
    id: 'emoji-pleading',
    emoji: '🥹',
    label: 'cảm kích',
    slug: 'cam-kich',
  },
  {
    id: 'emoji-party',
    emoji: '🥳',
    label: 'tuyệt vời',
    slug: 'tuyet-voi',
  },
  {
    id: 'emoji-christmas-tree',
    emoji: '🎄',
    label: 'vui vẻ',
    slug: 'vui-ve',
  },
  {
    id: 'emoji-smile-big',
    emoji: '😄',
    label: 'cười lớn',
    slug: 'cuoi-lon',
  },
  {
    id: 'emoji-smile-wide',
    emoji: '😃',
    label: 'vui vẻ',
    slug: 'vui-ve',
  },
  {
    id: 'emoji-smile-sweat',
    emoji: '😅',
    label: 'cười hơi lo lắng',
    slug: 'cuoi-hoi-lo-lang',
  },
  {
    id: 'emoji-joy',
    emoji: '😂',
    label: 'cười nước mắt',
    slug: 'cuoi-nuoc-mat',
  },
  {
    id: 'emoji-rolling-laugh',
    emoji: '🤣',
    label: 'cười lăn lộn',
    slug: 'cuoi-lan-lon',
  },
  {
    id: 'emoji-wink',
    emoji: '😉',
    label: 'nháy mắt',
    slug: 'nhay-mat',
  },
  {
    id: 'emoji-cool',
    emoji: '😎',
    label: 'ngầu',
    slug: 'ngau',
  },
  {
    id: 'emoji-nerd',
    emoji: '🤓',
    label: 'thông minh',
    slug: 'thong-minh',
  },
  {
    id: 'emoji-smirk',
    emoji: '😏',
    label: 'mỉa mai',
    slug: 'mia-mai',
  },
  {
    id: 'emoji-unamused',
    emoji: '😒',
    label: 'không hài lòng',
    slug: 'khong-hai-long',
  },
  {
    id: 'emoji-disappointed',
    emoji: '😞',
    label: 'thất vọng',
    slug: 'that-vong',
  },
  {
    id: 'emoji-worried',
    emoji: '😟',
    label: 'lo lắng',
    slug: 'lo-lang',
  },
  {
    id: 'emoji-confused',
    emoji: '😕',
    label: 'bối rối',
    slug: 'boi-roi',
  },
  {
    id: 'emoji-slight-frown',
    emoji: '🙁',
    label: 'hơi buồn',
    slug: 'hoi-buon',
  },
  {
    id: 'emoji-frown',
    emoji: '☹️',
    label: 'buồn',
    slug: 'buon',
  },
  {
    id: 'emoji-persevere',
    emoji: '😣',
    label: 'đau khổ',
    slug: 'dau-kho',
  },
  {
    id: 'emoji-confounded',
    emoji: '😖',
    label: 'bực bội',
    slug: 'buc-boi',
  },
  {
    id: 'emoji-tired',
    emoji: '😫',
    label: 'mệt mỏi',
    slug: 'met-moi',
  },
  {
    id: 'emoji-weary',
    emoji: '😩',
    label: 'kiệt sức',
    slug: 'kiet-suc',
  },
  {
    id: 'emoji-pleading-face',
    emoji: '🥺',
    label: 'van nài',
    slug: 'van-nai',
  },
  {
    id: 'emoji-cry',
    emoji: '😢',
    label: 'khóc',
    slug: 'khoc',
  },
  {
    id: 'emoji-sob',
    emoji: '😭',
    label: 'khóc nức nở',
    slug: 'khoc-nuc-no',
  },
  {
    id: 'emoji-triumph',
    emoji: '😤',
    label: 'tự hào',
    slug: 'tu-hao',
  },
  {
    id: 'emoji-angry',
    emoji: '😠',
    label: 'giận dữ',
    slug: 'gian-du',
  },
  {
    id: 'emoji-rage',
    emoji: '😡',
    label: 'rất giận',
    slug: 'rat-gian',
  },
  {
    id: 'emoji-cursing',
    emoji: '🤬',
    label: 'chửi thề',
    slug: 'chui-the',
  },
  {
    id: 'emoji-exploding-head',
    emoji: '🤯',
    label: 'nổ não',
    slug: 'no-nao',
  },
  {
    id: 'emoji-flushed',
    emoji: '😳',
    label: 'sửng sốt',
    slug: 'sung-sot',
  },
  {
    id: 'emoji-hot-face',
    emoji: '🥵',
    label: 'nóng bức',
    slug: 'nong-buc',
  },
  {
    id: 'emoji-cold-face',
    emoji: '🥶',
    label: 'lạnh cóng',
    slug: 'lanh-cong',
  },
  {
    id: 'emoji-scream',
    emoji: '😱',
    label: 'hoảng sợ',
    slug: 'hoang-so',
  },
  {
    id: 'emoji-fearful',
    emoji: '😨',
    label: 'sợ hãi',
    slug: 'so-hai',
  },
  {
    id: 'emoji-anxious',
    emoji: '😰',
    label: 'lo sợ',
    slug: 'lo-so',
  },
  {
    id: 'emoji-disappointed-relieved',
    emoji: '😥',
    label: 'buồn bã',
    slug: 'buon-ba',
  },
  {
    id: 'emoji-downcast',
    emoji: '😓',
    label: 'mệt mỏi',
    slug: 'met-moi',
  },
  {
    id: 'emoji-hugging',
    emoji: '🤗',
    label: 'ôm',
    slug: 'om',
  },
  {
    id: 'emoji-thinking',
    emoji: '🤔',
    label: 'suy nghĩ',
    slug: 'suy-nghi',
  },
  {
    id: 'emoji-hand-over-mouth',
    emoji: '🤭',
    label: 'bí mật',
    slug: 'bi-mat',
  },
  {
    id: 'emoji-shushing',
    emoji: '🤫',
    label: 'im lặng',
    slug: 'im-lang',
  },
  {
    id: 'emoji-lying',
    emoji: '🤥',
    label: 'nói dối',
    slug: 'noi-doi',
  },
  {
    id: 'emoji-no-mouth',
    emoji: '😶',
    label: 'không nói',
    slug: 'khong-noi',
  },
  {
    id: 'emoji-neutral',
    emoji: '😐',
    label: 'bình thường',
    slug: 'binh-thuong',
  },
  {
    id: 'emoji-expressionless',
    emoji: '😑',
    label: 'chán',
    slug: 'chan',
  },
  {
    id: 'emoji-hushed',
    emoji: '😯',
    label: 'ngạc nhiên',
    slug: 'ngac-nhien',
  },
  {
    id: 'emoji-frown-open',
    emoji: '😦',
    label: 'buồn ngạc nhiên',
    slug: 'buon-ngac-nhien',
  },
  {
    id: 'emoji-anguished',
    emoji: '😧',
    label: 'đau đớn',
    slug: 'dau-don',
  },
  {
    id: 'emoji-open-mouth',
    emoji: '😮',
    label: 'mở miệng',
    slug: 'mo-mieng',
  },
  {
    id: 'emoji-astonished',
    emoji: '😲',
    label: 'ngạc nhiên',
    slug: 'ngac-nhien',
  },
  {
    id: 'emoji-sleeping',
    emoji: '😴',
    label: 'ngủ',
    slug: 'ngu',
  },
  {
    id: 'emoji-drooling',
    emoji: '🤤',
    label: 'chảy nước dãi',
    slug: 'chay-nuoc-dai',
  },
  {
    id: 'emoji-sleepy',
    emoji: '😪',
    label: 'buồn ngủ',
    slug: 'buon-ngu',
  },
  {
    id: 'emoji-dizzy',
    emoji: '😵',
    label: 'chóng mặt',
    slug: 'chong-mat',
  },
  {
    id: 'emoji-zipper-mouth',
    emoji: '🤐',
    label: 'miệng khóa',
    slug: 'mieng-khoa',
  },
  {
    id: 'emoji-woozy',
    emoji: '🥴',
    label: 'say rượu',
    slug: 'say-ruou',
  },
  {
    id: 'emoji-dizzy-face',
    emoji: '😵‍💫',
    label: 'hoa mắt',
    slug: 'hoa-mat',
  },
];

export default emojiData;
